### ISSUE TITLE
[Feature] Placeholders without a function & customizable materials in GUI menu's

### ISSUE THREAD

**Issue by JorisvD01** [SpyG-Studios/spyg-chestshop#5]
Heya!

I'd like to see these 2 features added in the plugin. Mainly the placeholders (you you can for example set gray_stained_glass_pane as a background), if possible by setting a range of slots. For example;

_example:_
```
placeholder:
  material: GRAY_STAINED_GLASS_PANE
  slots:
  - 0-12
  - 14
  - 16
  - 17-26
```
 
The second idea is to make placeholder items configurable. For example where the GOLD_INGOT or BELL are currently hardcoded in the menu, make these configurable as a material in the config as well :)

Thanks for taking these into consideration. Cheers!
